### ISSUE TITLE
Django 2.0: Smartfields can't be installed properly

### ISSUE THREAD

**Issue by defaultUser3214** [lehins/django-smartfields#12]
Hello,
I've tried to install django-smartfields in the version 1.0.7 in a django 2.0 framework by executing the command pip install django-smartfields. Unfortunately I get the following Runtime Error doing 	venv/bin/python src/manage.py runserver 

> RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

In my readonly settings.py file the `SITE_ID =1` and `INSTALLED_APPS` contains a field called 'smartfileds'

```
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    
    'smartfields',
    'crispy_forms',
    'test_app',
    'test_suite',
)
```

Could you please have a look at the issue because I would need smartfields quite urgently.
Thanks a lot in advance!

**Comment by lehins** [comment]
@defaultUser3214 I assume you figure out what the issue was. Could you please share it here with others, so in case someone else stumbles upon the same problem they will know what to do?

**Comment by defaultUser3214** [comment]
Yes, I forgot to add 'smartfields' to the config -> settings->common.py and write it in the INSTALLED_APPS there and I thought that it was a trivial mistake. After I did this I got lots of other errors!! For example that django.contrib.sites and django.core.urlresolver and test_app could not be found by executing the unit test. The tests and everything worked well before using smartfield. In the following I posted my INSTALLED_APPS list and the output error of the unit tests: 

Extract of the unit test output error:

ERROR: tests.test_app.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_app.tests
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/stephanie/Dokumente/Uni/seeder/Lernplattform_Webseite/venv/lib/python3.5/site-packages/tests/test_app/tests/__init__.py", line 1, in <module>
    from test_suite.test_crispy import *
ImportError: No module named 'test_suite'

My INSTALLED_APPS:

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'social_django',
    'course',
    'task',
    'desk',
    'catalog',
    'prerequisite',
    'administration',
    'debug_toolbar',
    'martor',
    'avatar',
    'crispy_forms',
    'smartfield',
]

**Comment by lehins** [comment]
I've fixed support for `Django=2.x` in `django-smartfields=1.1.0`, there shouldn't be any issues in that regard.

As far as the error from the comment:
> ImportError: No module named 'test_suite'

I am not sure why you need to run `django-smartfields` tests as part of your project. Test suite passes on it's own (see `runtests.py`), since it uses a separate django project. See `tests/settings.py` if you still want to have the test suite embedded into your project, but I really don't see a reason for it.
