### ISSUE TITLE
FFMPEGProcessor not working

### ISSUE THREAD

**Issue by ramon90** [lehins/django-smartfields#19]
I used the code as in the docs for video processing, but it throws this error:
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
I have ffmpeg installed and I can import and use it.

**Comment by lehins** [comment]
I'd need a bit more information in order to attempt to help you. Clearly the error is due to django-smartfields not finding `ffmpeg`, which means that the django application doesn't have it on the `PATH`.  When you say you can import `ffmpeg`, do you mean you can use it as a C library, but can you actually run `ffmpeg` from the terminal? What's the setup like, what is the OS, there are too many moving components.

If you do have ffmpeg  installed, but it is not your `PATH`, then one nice and easy way you can work around this problem is to pass and adjusted `cmd_template` to the `FFMPEGProcessor(cmd_template=...)`, where the original template is here: https://github.com/lehins/django-smartfields/blob/b2d7ff1d7c9e97ed17d98abee53b93195145e87e/smartfields/processors/video.py#L15

**Comment by ramon90** [comment]
@lehins Thanks for your time. I can import ffmpeg (ffmpeg-python) in any file in my django app, and use. I am using OSX.
Should the cmd_template be like this adjusting the variables?  uri = fields.FileField(dependencies=[
        dependencies.FileDependency(suffix='mp4', processor=FFMPEGProcessor(
            cmd_template= "ffmpeg -i {input} -y -codec:v {vcodec} -b:v {vbitrate} " \
                   "-maxrate {maxrate} -bufsize {bufsize} -vf " \
                   "scale={width}:{height} -threads {threads} -c:a {acodec} {output}",))])
If so, then what should {input} be?

**Comment by lehins** [comment]
@ramon90 `django-smartfields` doesn't use ffmpeg as a library, but rather spawns it as a process, so you need to make sure you have it installed. Let me know what you get when you run this in your terminal:
```
$ ffmpeg -version
```

**Comment by lehins** [comment]
And this:
```
$ which ffmpeg
```

**Comment by ramon90** [comment]
`-bash: ffmpeg: command not found
`
`$ which ffmpeg ` returns nothing

**Comment by ramon90** [comment]
should not it be `$ pip show ffmpeg` to get the version of a pip package?
The above returns `Name: ffmpeg
Version: 1.4
Summary: ffmpeg python package url [https://github.com/jiashaokun/ffmpeg]
Home-page: https://github.com/jiashaokun/ffmpeg
Author: SkeyJIA
Author-email: 363604236@qq.com
License: MIT Licence
Location: /Users/mymac/Dev/STiiiCK/env/lib/python3.6/site-packages
Requires: 
Required-by: 
`

**Comment by lehins** [comment]
That's your problem. You don't have ffmpeg installed. Depending on the OS, you journey on getting it installed will be different. What's yours?

On ubuntu you'd run `sudo apt-get install ffmpeg`

**Comment by ramon90** [comment]
I am running Mac OSX. I run `pip install ffmpeg` to install it, and it installed successfully. Am I missing something?

**Comment by lehins** [comment]
Yes, you are missing something. with `pip install` you install python packages. [FFmpeg](https://ffmpeg.org) is not a python package, it's a tool written in C. That also happens to be a C library and can be used from other languages, like python through FFI, which is what python [`ffmpeg`](https://github.com/jiashaokun/ffmpeg) package does. When I wrote `django-smartfields`, python package `ffmpeg` didn't exist, so I had to use `ffmpeg` binary directly. Therefore you need to install `ffmpeg` tool, the one that you can run from the terminal. On mac osx, I believe you can easily get it done with `brew`, see this gist: https://gist.github.com/clayton/6196167

**Comment by lehins** [comment]
I stand corrected, [`ffmpeg`](https://github.com/jiashaokun/ffmpeg/blob/master/ffmpeg/video.py#L271) package does not use FFI. So if you'd use that package, you'd get exactly the same error message. So get the actual `ffmpeg` installed and you'll be good.

**Comment by ramon90** [comment]
@lehins Oh well, thanks a lot.

**Comment by ramon90** [comment]
Hello @lehins, I have asked you before about how to get this library working. I would like to know how can I use it compress a video. I tried using the following code from the docs
`uri = fields.FileField(upload_to='videos/', dependencies=[
        dependencies.FileDependency(suffix='mp4', processor=FFMPEGProcessor(
            vbitrate='1M',
            maxrate='1M',
            bufsize='2M',
            width='trunc(oh*a/2)*2',  # http://ffmpeg.org/ffmpeg-all.html#scale
            height=720,
            threads=0,  # use all cores
            abitrate='96k',
            format='mp4',
            vcodec='libx264',
            acodec='libfdk_aac'))])`
What happens is that the original video is uploaded normally and another .mp4 file is created which has a size of zero KB.
