### ISSUE TITLE
Django admin inlines

### ISSUE THREAD

**Issue by xtrinch** [lehins/django-smartfields#7]
The images are not processed (resized) when uploaded through the django TabularInline form.

**Comment by lehins** [comment]
It could be that Django does some bulk update with TabularInline form, but I will have to investigate it in more detail. Is it possible that you can include relevant code snippets, it would be very helpful.

**Comment by xtrinch** [comment]
```
class Photo(models.Model):
    photo = fields.ImageField(upload_to='static/photos', null=True, dependencies=[
        FileDependency(processor=ImageProcessor(
            format='JPEG', scale={'max_width': 300, 'max_height': 300}))
    ])

class PhotoInline(admin.TabularInline):
    model = Photo
    extra = 0

class RatingAdmin(admin.ModelAdmin):
    list_display = ('id','rating_date','token_user', 'token_shop', 'rating')

    inlines = [
        PhotoInline
    ]

```

**Comment by lehins** [comment]
@xtrinch, thank you. I'll look into the problem this weekend.

**Comment by andybak** [comment]
I'm fairly certain inlines don't trigger any bulk ORM actions (which would bypass smartfields)

**Comment by lehins** [comment]
@andybak, yes bulk ORM actions would bypass smartfields.

**Comment by lehins** [comment]
@xtrinch, unfortunately I cannot replicate your problem.
I've created same models and used same code for admin. Attached is the screenshot. Images are converted and resized as expected.
What's the version of Django you are using and version of Pillow library?
Does it resize images when you upload using regular forms?

![screenshot from 2016-02-11 17-59-05](https://cloud.githubusercontent.com/assets/2333894/12996037/6a726080-d0e9-11e5-8d2a-c1bd8c311169.png)

**Comment by lehins** [comment]
@xtrinch, as a side note and unrelated to this issue, you shouldn't use `null=True` on file fields, use `blank=True` instead, since as far as database is concerned it is simple `VARCHAR` field.
https://docs.djangoproject.com/en/1.9/ref/models/fields/#null

**Comment by lehins** [comment]
I guess I am closing the issue since it cannot be replicated.
